### ISSUE TITLE
`Cannot find a valid source` in demo.rs

### ISSUE THREAD

**Issue by marc-trius** [a1phyr/ggez-assets_manager#2]
I am getting the following error when running the demo:

```
ERROR ggez::event] Error on EventHandler::draw(): ResourceLoadError("\"fonts.DejaVuSans\": Custom { kind: Other, error: \"Cannot find a valid source\" }")
Error on EventHandler::draw(): ResourceLoadError("\"fonts.DejaVuSans\": Custom { kind: Other, error: \"Cannot find a valid source\" }")
```

**Comment by a1phyr** [comment]
I investigated a bit and I found out that `ggez` looks for resources in the directory of the executable, not the current directory ! 

Additionally, it turned out to work on my machine because I copied the asset directory to `~/.local/ggez` during previous tests :sweat_smile: 

As a workaround for now you can do something like

```sh
cargo build --exemple demo --features hot-reloading && cp target/debug/examples/demo . && ./demo
``` 
or create a symlink

**Comment by marc-trius** [comment]
Thanks! I had the resource directory set up a little differently in my project (see https://github.com/ggez/ggez/blob/8504318a97174bda261d2f233a191d8df3815334/examples/03_drawing.rs#L189), but modeling it after your updated example fixed the issue. If you have time and an idea of why this is, I would appreciate an explanation.
